// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/package_registry/versionRecord.proto

package package_registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionRecordProto struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Tag                   string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	DomainName            string                 `protobuf:"bytes,2,opt,name=domainName,proto3" json:"domainName,omitempty"`
	PackageName           string                 `protobuf:"bytes,3,opt,name=packageName,proto3" json:"packageName,omitempty"`
	Version               string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	BlobHash              []byte                 `protobuf:"bytes,5,opt,name=blobHash,proto3" json:"blobHash,omitempty"`
	PreviousVersionRecord []byte                 `protobuf:"bytes,6,opt,name=previousVersionRecord,proto3" json:"previousVersionRecord,omitempty"`
	Sig                   []byte                 `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VersionRecordProto) Reset() {
	*x = VersionRecordProto{}
	mi := &file_internal_package_registry_versionRecord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRecordProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRecordProto) ProtoMessage() {}

func (x *VersionRecordProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_package_registry_versionRecord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRecordProto.ProtoReflect.Descriptor instead.
func (*VersionRecordProto) Descriptor() ([]byte, []int) {
	return file_internal_package_registry_versionRecord_proto_rawDescGZIP(), []int{0}
}

func (x *VersionRecordProto) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *VersionRecordProto) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *VersionRecordProto) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *VersionRecordProto) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionRecordProto) GetBlobHash() []byte {
	if x != nil {
		return x.BlobHash
	}
	return nil
}

func (x *VersionRecordProto) GetPreviousVersionRecord() []byte {
	if x != nil {
		return x.PreviousVersionRecord
	}
	return nil
}

func (x *VersionRecordProto) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

var File_internal_package_registry_versionRecord_proto protoreflect.FileDescriptor

const file_internal_package_registry_versionRecord_proto_rawDesc = "" +
	"\n" +
	"-internal/package_registry/versionRecord.proto\x12\x11pacakage_registry\"\xe6\x01\n" +
	"\x12VersionRecordProto\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1e\n" +
	"\n" +
	"domainName\x18\x02 \x01(\tR\n" +
	"domainName\x12 \n" +
	"\vpackageName\x18\x03 \x01(\tR\vpackageName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1a\n" +
	"\bblobHash\x18\x05 \x01(\fR\bblobHash\x124\n" +
	"\x15previousVersionRecord\x18\x06 \x01(\fR\x15previousVersionRecord\x12\x10\n" +
	"\x03sig\x18\a \x01(\fR\x03sigBAZ?github.com/RasmusKebert/D7024E_Grupp6/internal/package_registryb\x06proto3"

var (
	file_internal_package_registry_versionRecord_proto_rawDescOnce sync.Once
	file_internal_package_registry_versionRecord_proto_rawDescData []byte
)

func file_internal_package_registry_versionRecord_proto_rawDescGZIP() []byte {
	file_internal_package_registry_versionRecord_proto_rawDescOnce.Do(func() {
		file_internal_package_registry_versionRecord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_package_registry_versionRecord_proto_rawDesc), len(file_internal_package_registry_versionRecord_proto_rawDesc)))
	})
	return file_internal_package_registry_versionRecord_proto_rawDescData
}

var file_internal_package_registry_versionRecord_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_package_registry_versionRecord_proto_goTypes = []any{
	(*VersionRecordProto)(nil), // 0: pacakage_registry.VersionRecordProto
}
var file_internal_package_registry_versionRecord_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_package_registry_versionRecord_proto_init() }
func file_internal_package_registry_versionRecord_proto_init() {
	if File_internal_package_registry_versionRecord_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_package_registry_versionRecord_proto_rawDesc), len(file_internal_package_registry_versionRecord_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_package_registry_versionRecord_proto_goTypes,
		DependencyIndexes: file_internal_package_registry_versionRecord_proto_depIdxs,
		MessageInfos:      file_internal_package_registry_versionRecord_proto_msgTypes,
	}.Build()
	File_internal_package_registry_versionRecord_proto = out.File
	file_internal_package_registry_versionRecord_proto_goTypes = nil
	file_internal_package_registry_versionRecord_proto_depIdxs = nil
}
