package network

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"log"
	"sync"
	"sync/atomic"
)

/*
The node does not implement Kademlia routing, lookups, or data storage.
It only provides the communication endpoint that Kademlia can use.
*/

// Node provides a unified abstraction for both sending and receiving messages.
type Node struct {
	ID         string
	addr       Address
	network    Network
	connection Connection
	handlers   map[string]MessageHandler
	// mu protects the handler map while handlers are registered or looked up.
	mu     sync.RWMutex
	closed bool
	// closeMu protects the node lifecycle flag shared by Start and Close.
	closeMu       sync.RWMutex
	nextRequestID uint64
}

// MessageHandler processes incoming messages.
type MessageHandler func(msg Message) error

// NewNode creates a new node that can send and receive messages.
func NewNode(network Network, addr Address) (*Node, error) {
	connection, err := network.Listen(addr)
	if err != nil {
		return nil, fmt.Errorf("failed to create node: %w", err)
	}

	id := hashIPPort(addr.IP, addr.Port)

	return &Node{
		ID:         id,
		addr:       addr,
		network:    network,
		connection: connection,
		handlers:   make(map[string]MessageHandler),
	}, nil
}

// ID = hash(Ip|Port)
func hashIPPort(ip string, port int) string {
	//is | supposed to be the char "|" or an or operation?
	input := fmt.Sprintf("%s|%d", ip, port)
	sum := sha256.Sum256([]byte(input))
	return hex.EncodeToString(sum[:])
}

func (n *Node) nextID() uint64 {
	// Atomic increment keeps request IDs unique when multiple senders use the
	// same node concurrently without taking the broader node mutex.
	return atomic.AddUint64(&n.nextRequestID, 1) //The first request ID generated by a new node is 1, not 0.
}

// Handle registers a message handler for a specific message type.
func (n *Node) Handle(msgType string, handler MessageHandler) {
	// Lock registration because it may happen while the receive goroutine is
	// reading the handler map.
	n.mu.Lock()
	defer n.mu.Unlock()
	n.handlers[msgType] = handler
}

// Start begins listening for incoming messages.
func (n *Node) Start() {
	// Each node receives independently so waiting for one node's traffic does
	// not block other nodes in the simulated network.
	go func() {
		for {
			// Read-lock the lifecycle flag because Close may update it concurrently.
			n.closeMu.RLock()
			if n.closed {
				n.closeMu.RUnlock()
				return
			}
			n.closeMu.RUnlock()

			// Recv blocks on the message or shutdown channel instead of busy-waiting.
			msg, err := n.connection.Recv()
			if err != nil {
				n.closeMu.RLock()
				if !n.closed {
					log.Printf("Node %s failed to receive message: %v", n.addr.String(), err)
				}
				n.closeMu.RUnlock()
				return
			}

			//Extracts msg type if it has one
			msgType := msg.Type
			if msgType == "" {
				payload := string(msg.Payload)
				for i, ch := range payload {
					if ch == ':' {
						msgType = payload[:i]
						break
					}
				}
			}
			if msgType == "" {
				msgType = "default"
			}

			// A read lock allows concurrent message handling while preventing a
			// handler registration from modifying the map during lookup.
			n.mu.RLock()
			handler, exists := n.handlers[msgType]
			if !exists {
				handler, exists = n.handlers["default"]
			}
			n.mu.RUnlock()

			if exists && handler != nil {
				if err := handler(msg); err != nil {
					log.Printf("handler error: %v", err)
				}
			}
		}
	}()
}

// Send sends a message to the target address.
func (n *Node) Send(to Address, msgType string, data []byte) error {
	connection, err := n.network.Dial(to)
	if err != nil {
		return fmt.Errorf("failed to dial %s: %v", to.String(), err)
	}
	defer connection.Close()

	var payload []byte
	if msgType != "" {
		payload = append([]byte(msgType+":"), data...)
	} else {
		payload = data
	}

	msg := Message{
		From:      n.addr,
		To:        to,
		Type:      msgType,
		Payload:   payload,
		RequestID: n.nextID(),
		network:   n.network,
	}

	return connection.Send(msg)
}

// SendString is a convenience method for sending string messages.
func (n *Node) SendString(to Address, msgType, data string) error {
	return n.Send(to, msgType, []byte(data))
}

// Close shuts down the node.
func (n *Node) Close() error {
	// Lock the lifecycle state so Start observes a complete shutdown transition.
	n.closeMu.Lock()
	n.closed = true
	n.closeMu.Unlock()
	return n.connection.Close()
}

// Address returns the node's address.
func (n *Node) Address() Address {
	return n.addr
}
