// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: message.proto

package kademlia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactProto) Reset() {
	*x = ContactProto{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactProto) ProtoMessage() {}

func (x *ContactProto) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactProto.ProtoReflect.Descriptor instead.
func (*ContactProto) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *ContactProto) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ContactProto) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type MessageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	From          *ContactProto          `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Target        []byte                 `protobuf:"bytes,5,opt,name=Target,proto3" json:"Target,omitempty"`
	Contacts      []*ContactProto        `protobuf:"bytes,6,rep,name=Contacts,proto3" json:"Contacts,omitempty"`
	Value         []byte                 `protobuf:"bytes,7,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageProto) Reset() {
	*x = MessageProto{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProto) ProtoMessage() {}

func (x *MessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProto.ProtoReflect.Descriptor instead.
func (*MessageProto) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageProto) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MessageProto) GetFrom() *ContactProto {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MessageProto) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MessageProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MessageProto) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *MessageProto) GetContacts() []*ContactProto {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *MessageProto) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\bkademlia\"8\n" +
	"\fContactProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xde\x01\n" +
	"\fMessageProto\x12\x1c\n" +
	"\tMessageId\x18\x01 \x01(\fR\tMessageId\x12*\n" +
	"\x04From\x18\x02 \x01(\v2\x16.kademlia.ContactProtoR\x04From\x12\x0e\n" +
	"\x02To\x18\x03 \x01(\tR\x02To\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\tR\x04Type\x12\x16\n" +
	"\x06Target\x18\x05 \x01(\fR\x06Target\x122\n" +
	"\bContacts\x18\x06 \x03(\v2\x16.kademlia.ContactProtoR\bContacts\x12\x14\n" +
	"\x05Value\x18\a \x01(\fR\x05ValueB9Z7github.com/RasmusKebert/D7024E_Grupp6/internal/kademliab\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_proto_goTypes = []any{
	(*ContactProto)(nil), // 0: kademlia.ContactProto
	(*MessageProto)(nil), // 1: kademlia.MessageProto
}
var file_message_proto_depIdxs = []int32{
	0, // 0: kademlia.MessageProto.From:type_name -> kademlia.ContactProto
	0, // 1: kademlia.MessageProto.Contacts:type_name -> kademlia.ContactProto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
