// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: internal/kademlia/message.proto

package kademlia

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreMode int32

const (
	StoreMode_IMMUTABLE      StoreMode = 0
	StoreMode_MUTABLE_LATEST StoreMode = 1
)

// Enum value maps for StoreMode.
var (
	StoreMode_name = map[int32]string{
		0: "IMMUTABLE",
		1: "MUTABLE_LATEST",
	}
	StoreMode_value = map[string]int32{
		"IMMUTABLE":      0,
		"MUTABLE_LATEST": 1,
	}
)

func (x StoreMode) Enum() *StoreMode {
	p := new(StoreMode)
	*p = x
	return p
}

func (x StoreMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_kademlia_message_proto_enumTypes[0].Descriptor()
}

func (StoreMode) Type() protoreflect.EnumType {
	return &file_internal_kademlia_message_proto_enumTypes[0]
}

func (x StoreMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreMode.Descriptor instead.
func (StoreMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_kademlia_message_proto_rawDescGZIP(), []int{0}
}

type ContactProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactProto) Reset() {
	*x = ContactProto{}
	mi := &file_internal_kademlia_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactProto) ProtoMessage() {}

func (x *ContactProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_kademlia_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactProto.ProtoReflect.Descriptor instead.
func (*ContactProto) Descriptor() ([]byte, []int) {
	return file_internal_kademlia_message_proto_rawDescGZIP(), []int{0}
}

func (x *ContactProto) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ContactProto) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type MessageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     []byte                 `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	From          *ContactProto          `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Target        []byte                 `protobuf:"bytes,5,opt,name=Target,proto3" json:"Target,omitempty"`
	Contacts      []*ContactProto        `protobuf:"bytes,6,rep,name=Contacts,proto3" json:"Contacts,omitempty"`
	Value         []byte                 `protobuf:"bytes,7,opt,name=Value,proto3" json:"Value,omitempty"`
	StoreMode     StoreMode              `protobuf:"varint,8,opt,name=store_mode,json=storeMode,proto3,enum=kademlia.StoreMode" json:"store_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageProto) Reset() {
	*x = MessageProto{}
	mi := &file_internal_kademlia_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProto) ProtoMessage() {}

func (x *MessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_kademlia_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProto.ProtoReflect.Descriptor instead.
func (*MessageProto) Descriptor() ([]byte, []int) {
	return file_internal_kademlia_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageProto) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MessageProto) GetFrom() *ContactProto {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MessageProto) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MessageProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MessageProto) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *MessageProto) GetContacts() []*ContactProto {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *MessageProto) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MessageProto) GetStoreMode() StoreMode {
	if x != nil {
		return x.StoreMode
	}
	return StoreMode_IMMUTABLE
}

type VersionRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Domain             string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Package            string                 `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	Version            string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BlobHash           []byte                 `protobuf:"bytes,4,opt,name=blob_hash,json=blobHash,proto3" json:"blob_hash,omitempty"`
	PreviousRecordHash []byte                 `protobuf:"bytes,5,opt,name=previous_record_hash,json=previousRecordHash,proto3" json:"previous_record_hash,omitempty"`
	Signature          []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VersionRecord) Reset() {
	*x = VersionRecord{}
	mi := &file_internal_kademlia_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRecord) ProtoMessage() {}

func (x *VersionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_kademlia_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRecord.ProtoReflect.Descriptor instead.
func (*VersionRecord) Descriptor() ([]byte, []int) {
	return file_internal_kademlia_message_proto_rawDescGZIP(), []int{2}
}

func (x *VersionRecord) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *VersionRecord) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *VersionRecord) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionRecord) GetBlobHash() []byte {
	if x != nil {
		return x.BlobHash
	}
	return nil
}

func (x *VersionRecord) GetPreviousRecordHash() []byte {
	if x != nil {
		return x.PreviousRecordHash
	}
	return nil
}

func (x *VersionRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type LatestPointer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Domain            string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Package           string                 `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	Version           string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	VersionRecordHash []byte                 `protobuf:"bytes,4,opt,name=version_record_hash,json=versionRecordHash,proto3" json:"version_record_hash,omitempty"`
	Signature         []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LatestPointer) Reset() {
	*x = LatestPointer{}
	mi := &file_internal_kademlia_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestPointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestPointer) ProtoMessage() {}

func (x *LatestPointer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_kademlia_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestPointer.ProtoReflect.Descriptor instead.
func (*LatestPointer) Descriptor() ([]byte, []int) {
	return file_internal_kademlia_message_proto_rawDescGZIP(), []int{3}
}

func (x *LatestPointer) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *LatestPointer) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *LatestPointer) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LatestPointer) GetVersionRecordHash() []byte {
	if x != nil {
		return x.VersionRecordHash
	}
	return nil
}

func (x *LatestPointer) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RegistryRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Record:
	//
	//	*RegistryRecord_VersionRecord
	//	*RegistryRecord_LatestPointer
	Record        isRegistryRecord_Record `protobuf_oneof:"record"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRecord) Reset() {
	*x = RegistryRecord{}
	mi := &file_internal_kademlia_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRecord) ProtoMessage() {}

func (x *RegistryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_kademlia_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRecord.ProtoReflect.Descriptor instead.
func (*RegistryRecord) Descriptor() ([]byte, []int) {
	return file_internal_kademlia_message_proto_rawDescGZIP(), []int{4}
}

func (x *RegistryRecord) GetRecord() isRegistryRecord_Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *RegistryRecord) GetVersionRecord() *VersionRecord {
	if x != nil {
		if x, ok := x.Record.(*RegistryRecord_VersionRecord); ok {
			return x.VersionRecord
		}
	}
	return nil
}

func (x *RegistryRecord) GetLatestPointer() *LatestPointer {
	if x != nil {
		if x, ok := x.Record.(*RegistryRecord_LatestPointer); ok {
			return x.LatestPointer
		}
	}
	return nil
}

type isRegistryRecord_Record interface {
	isRegistryRecord_Record()
}

type RegistryRecord_VersionRecord struct {
	VersionRecord *VersionRecord `protobuf:"bytes,1,opt,name=version_record,json=versionRecord,proto3,oneof"`
}

type RegistryRecord_LatestPointer struct {
	LatestPointer *LatestPointer `protobuf:"bytes,2,opt,name=latest_pointer,json=latestPointer,proto3,oneof"`
}

func (*RegistryRecord_VersionRecord) isRegistryRecord_Record() {}

func (*RegistryRecord_LatestPointer) isRegistryRecord_Record() {}

var File_internal_kademlia_message_proto protoreflect.FileDescriptor

const file_internal_kademlia_message_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/kademlia/message.proto\x12\bkademlia\"8\n" +
	"\fContactProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x92\x02\n" +
	"\fMessageProto\x12\x1c\n" +
	"\tMessageId\x18\x01 \x01(\fR\tMessageId\x12*\n" +
	"\x04From\x18\x02 \x01(\v2\x16.kademlia.ContactProtoR\x04From\x12\x0e\n" +
	"\x02To\x18\x03 \x01(\tR\x02To\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\tR\x04Type\x12\x16\n" +
	"\x06Target\x18\x05 \x01(\fR\x06Target\x122\n" +
	"\bContacts\x18\x06 \x03(\v2\x16.kademlia.ContactProtoR\bContacts\x12\x14\n" +
	"\x05Value\x18\a \x01(\fR\x05Value\x122\n" +
	"\n" +
	"store_mode\x18\b \x01(\x0e2\x13.kademlia.StoreModeR\tstoreMode\"\xc8\x01\n" +
	"\rVersionRecord\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x18\n" +
	"\apackage\x18\x02 \x01(\tR\apackage\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tblob_hash\x18\x04 \x01(\fR\bblobHash\x120\n" +
	"\x14previous_record_hash\x18\x05 \x01(\fR\x12previousRecordHash\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\xa9\x01\n" +
	"\rLatestPointer\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x18\n" +
	"\apackage\x18\x02 \x01(\tR\apackage\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12.\n" +
	"\x13version_record_hash\x18\x04 \x01(\fR\x11versionRecordHash\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\x9e\x01\n" +
	"\x0eRegistryRecord\x12@\n" +
	"\x0eversion_record\x18\x01 \x01(\v2\x17.kademlia.VersionRecordH\x00R\rversionRecord\x12@\n" +
	"\x0elatest_pointer\x18\x02 \x01(\v2\x17.kademlia.LatestPointerH\x00R\rlatestPointerB\b\n" +
	"\x06record*.\n" +
	"\tStoreMode\x12\r\n" +
	"\tIMMUTABLE\x10\x00\x12\x12\n" +
	"\x0eMUTABLE_LATEST\x10\x01B9Z7github.com/RasmusKebert/D7024E_Grupp6/internal/kademliab\x06proto3"

var (
	file_internal_kademlia_message_proto_rawDescOnce sync.Once
	file_internal_kademlia_message_proto_rawDescData []byte
)

func file_internal_kademlia_message_proto_rawDescGZIP() []byte {
	file_internal_kademlia_message_proto_rawDescOnce.Do(func() {
		file_internal_kademlia_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_kademlia_message_proto_rawDesc), len(file_internal_kademlia_message_proto_rawDesc)))
	})
	return file_internal_kademlia_message_proto_rawDescData
}

var file_internal_kademlia_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_kademlia_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_kademlia_message_proto_goTypes = []any{
	(StoreMode)(0),         // 0: kademlia.StoreMode
	(*ContactProto)(nil),   // 1: kademlia.ContactProto
	(*MessageProto)(nil),   // 2: kademlia.MessageProto
	(*VersionRecord)(nil),  // 3: kademlia.VersionRecord
	(*LatestPointer)(nil),  // 4: kademlia.LatestPointer
	(*RegistryRecord)(nil), // 5: kademlia.RegistryRecord
}
var file_internal_kademlia_message_proto_depIdxs = []int32{
	1, // 0: kademlia.MessageProto.From:type_name -> kademlia.ContactProto
	1, // 1: kademlia.MessageProto.Contacts:type_name -> kademlia.ContactProto
	0, // 2: kademlia.MessageProto.store_mode:type_name -> kademlia.StoreMode
	3, // 3: kademlia.RegistryRecord.version_record:type_name -> kademlia.VersionRecord
	4, // 4: kademlia.RegistryRecord.latest_pointer:type_name -> kademlia.LatestPointer
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_kademlia_message_proto_init() }
func file_internal_kademlia_message_proto_init() {
	if File_internal_kademlia_message_proto != nil {
		return
	}
	file_internal_kademlia_message_proto_msgTypes[4].OneofWrappers = []any{
		(*RegistryRecord_VersionRecord)(nil),
		(*RegistryRecord_LatestPointer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_kademlia_message_proto_rawDesc), len(file_internal_kademlia_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_kademlia_message_proto_goTypes,
		DependencyIndexes: file_internal_kademlia_message_proto_depIdxs,
		EnumInfos:         file_internal_kademlia_message_proto_enumTypes,
		MessageInfos:      file_internal_kademlia_message_proto_msgTypes,
	}.Build()
	File_internal_kademlia_message_proto = out.File
	file_internal_kademlia_message_proto_goTypes = nil
	file_internal_kademlia_message_proto_depIdxs = nil
}
